"""
A `VTuber` scalar represents an entity of a virtual streamer, which contains information about its profile, such as its full name, its fan name, branch, assigned group, among others.
"""
type VTuber {
	_id: String
	fullname: String
	fanname: String
	quote: String
	nicknames: [String!]
	branch: String
	unit: String
	emoji: String
	youtube: String
	status: String
	avatar: String
	gender: String
	likes: [String!]
	dislikes: [String!]
	age: Int
	birthday: String
	zodiac: String
	height: Float
	hashtag: Hashtag
	socialNetworks: [SocialNetwork!]
	songs: [Song!]
}

"""
A group of Twitter (X) hashtags associated with a `VTuber` entity
"""
type Hashtag {
	_id: String
	general: String
	stream: String
	fanart: String
	memes: String
	vtuber: VTuber
}

type SocialNetwork {
	_id: String
	application: String
	accounturl: String
	vtuber: VTuber
}

type Song {
	_id: String
	name: String
	album: String
	releasedate: String
	compositor: String
	mixing: String
	lyrics: String
	vtuber: VTuber
}

# Queries
# *******

type Query {
	getVtuber(ID: ID!): VTuber
	getHashtag(ID: ID!): Hashtag
	getSocial(ID: ID!): SocialNetwork
	getSong(ID: ID!): Song
	hashtag: [Hashtag]
	socials: [SocialNetwork]
	songs: [Song]
	vtuber: [VTuber]
}

# Mutations
# *********

type Mutation {
	assignSongToVtuber(SNGID: ID!, VTID: ID!): VTuber!
	assignHashtagToVtuber(HTID: ID!, VTID: ID!): VTuber!
	assignSocialNetworkToVtuber(SNID: ID!, VTID: ID!): VTuber!
	addVtuber(
		fullname: String
		fanname: String
		quote: String
		nicknames: [String!]
		branch: String
		unit: String
		emoji: String
		youtube: String
		status: String
		avatar: String
		gender: String
		likes: [String!]
		dislikes: [String!]
		age: Int
		birthday: String
		zodiac: String
		height: Float
	): VTuber!
	addSong(
		name: String
		album: String
		releasedate: String
		compositor: String
		mixing: String
		lyrics: String
	): Song!
	addHashtag(general: String, stream: String, fanart: String, memes: String): Hashtag!
	addSocialNetwork(application: String, accounturl: String): SocialNetwork!
	deleteVtuber(ID: ID!): Boolean
	deleteHashtag(ID: ID!): Boolean
	deleteSocialNetwork(ID: ID!): Boolean
	deleteSong(ID: ID!): Boolean
	editVtuber(
		ID: ID!
		fullname: String
		fanname: String
		quote: String
		nicknames: [String!]
		branch: String
		unit: String
		emoji: String
		youtube: String
		avatar: String
		status: String
		gender: String
		likes: [String!]
		dislikes: [String!]
		age: Int
		birthday: String
		zodiac: String
		height: Float
	): Boolean
}
